version: "3.1"

services:

  php-fpm:

    image: webdevops/php-nginx:7.4
    container_name: myapp-webserver
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/webroot
    ports:
      - "80:80"

  mysql:

    image: mysql:5.6
    container_name: myapp-mysql
    working_dir: /app
    volumes:
      - .:/app
      - ./tmp/data/mysql_db:/var/lib/mysql
    env_file:
      - mysql.env
    command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;'
    ports:
      - "3306:3306"
  
  # node:
  #   image: "node:14"
  #   working_dir: /app
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./:/app
  #   expose:
  #     - "8081:8081"
  #   stdin_open: true
  #   tty: true
  #   depends_on: 
  #     - php-fpm
  #     - mysql
  #   command: sh -c "npm install cypress && npm run cy"
  cypress:
      image: "cypress/included:3.2.0"
      depends_on: 
        - php-fpm
        - mysql
      environment:
        - CYPRESS_baseUrl=http://php-fpm
      container_name: myapp-cypress

      working_dir: /app
      volumes:
        - ./:/app