
# name: Node.js CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
#     - name: Cypress run
#       uses: cypress-io/github-action@v2
#       with:
#         start: "npm run test"
#         wait-on: "http://localhost:8765"
#         # let's see if the Test Runner handles url in the config
#         # https://github.com/cypress-io/cypress/issues/5466
#         config: baseUrl=http://localhost:8765